---
#################################################################################################################
# The overall classification of this file is UNCLASSIFIED.
#
# NOTICE: This software was produced for the U. S. Government under Contract
# No. FA8702-19-C-0001, and is subject to the Rights in Noncommercial Computer
# Software and Noncommercial Computer Software Documentation Clause DFARS
# 252.227-7014 (FEB 2014)
#
# (c) 2023 The MITRE Corporation
#
# PROJECT: MVP - EKS Platform Deployment Prototype - Used to automate the deployment of EKS platform on AWS. 
#
# FILE: crossplane.yaml
# CLASSIFICATION: Unclassified
# AUTHORS:  Thomas Yang (tzyang@mitre.org), Karpagam Balan (kbalan@mitre.org)
# CREATED: January, 2023
# DESCRIPTION: yaml manifest part of Crossplane composite template to deploy EKS
###################################################################################################################
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: eks-distro-composition
spec:
  crossplane:
    version: ">=v1.12.0"
  dependsOn: []
